version: 0.2

phases:
  install:
    commands:
      - echo "Installing nvm..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 16
      - nvm use 16
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the project..."
      # Your build commands here, e.g.:
      - npm run build
      - cd dist
      - npm test
