version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 16..."
      - nvm install 16
      - nvm use 16
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the project..."
      # Your build commands here, e.g.:
      - npm run build
      - cd dist
      - npm test
